# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://jvillasr.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "" 

# Title of the Site
title: Jaime Villaseñor
# Description of the Site
description: Massive binary stars • spectroscopic surveys • stellar evolution
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/30dor.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: villasenor@mpia.de
facebook_username: jaimevillasr.astro
bluesky_handle: jvillasr.bsky.social
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username:  jvillasr
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /
orcid_username: 0000-0002-7984-1675

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Jaime I. Villaseñor
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: /assets/images/profilepic.png
# 60 Words About the Author
author-about: 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/jvillasr

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  # -
  #   scope:
  #     type: 'blogs'
  #   values:
  #     layout: blog
      # title: "BLOG"
      # permalink: /blog/
  -
    scope:
      type: 'pages'
    values:
      layout: page

  - scope:
      path: "projects"        # folder at repo root
      type: "pages"           # IMPORTANT so it applies to pages
    values:
      layout: project
      permalink: /projects/:basename/

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - notes/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
